---
name: Push to GCR GitHub Action

on:
  # run it on push to the default repository branch
  push:
    branches: [stg]
    
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: igor-pyo
          image_name: pyo-app
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop $(docker ps -q);
            docker pull igorka77/pyo:latest
            docker run -p=80:80 igorka77/pyo-app
